GET http://localhost:80/posts

###

GET http://localhost:80/posts/60db7f3a7b19de45bca4956c

###

PATCH https://wsb-blog-backend.herokuapp.com/posts/60db7f3a7b19de45bca4956c
Content-Type: application/json

{
    "postTitle": "Let's test it2!"
}

###

GET https://wsb-blog-backend.herokuapp.com/posts

###

POST http://localhost:80/user/register